#pragma once

#define MUSIC_MASK (keycode != KC_NO)

#define MIDI_ADVANCED

#define TAPPING_TERM 115

#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY          0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL       12
#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY    0
#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED      32
#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX    32
#undef MOUSEKEY_FRICTION
#define MOUSEKEY_FRICTION       30

#define MOUSEKEY_INERTIA

#undef MOUSEKEY_MOVE_DELTA
#define MOUSEKEY_MOVE_DELTA     1

#ifndef USB_MAX_POWER_CONSUMPTION
#define USB_MAX_POWER_CONSUMPTION 100
#endif
